FROM ubuntu:20.04

USER root
WORKDIR /root/

COPY ./ ./hznuoj-judge

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list \
  && bash /root/hznuoj-judge/install_sandbox.sh \
  && rm -rf /root/hznuoj-judge

CMD ["/bin/bash"]
